### ISSUE TITLE
Add feature to select multiple accounts.

### ISSUE THREAD

**Issue by amarjeetkapoor1** [GreatDevelopers/Conversations#11]
At present when we create account, we get option to invite people and clicking on any contact. It moves to messaging screen i.e. there is no option to add multiple accounts in starting. 
Even when inviting people to group we can invite single person and we have to repeat process of clicking on invite contact and then add a person. There should be option to select multiple persons and invite them together.

**Comment by jugrajsingh** [comment]
Yes there is.
