### ISSUE TITLE
Shareable URI for conference not working correctly

### ISSUE THREAD

**Issue by amarjeetkapoor1** [GreatDevelopers/Conversations#27]
When we share URI for conference the URI that we get is not correct and doesn't go to correct activity.

**Comment by jugrajsingh** [comment]
You mean share action from conference details page.

**Comment by jugrajsingh** [comment]
If that, works fine for me

**Comment by jugrajsingh** [comment]
I get that the issue is with the underscores.
It did not working with underscore for URIs of groups

**Comment by jugrajsingh** [comment]
Problem resolved.
Close the issue.
